### ISSUE TITLE
Sometimes proposal_idx was empty

### ISSUE THREAD

**Issue by kevinchan04** [aim-uofa/DyCo3D#11]
Hi, when I tried to run the inference code, I met a problem that the variable proposal_idx was empty. Could you give me any suggestion to debug the code? Thank you very much! The location of code and error information are listed below.

https://github.com/aim-uofa/DyCo3D/blob/17d22c2d839c0a1043fb72df301e3935af5ca0e9/model/pointgroup/pointgroup.py#L454

> Traceback (most recent call last):
  File "test_s3dis.py", line 276, in <module>
    test(model, model_fn, data_name, cfg.test_epoch)
  File "test_s3dis.py", line 70, in test
    preds = model_fn(batch, model, epoch)
  File "/home/xiaodchen/Generalization/DyCo3D/model/pointgroup/pointgroup.py", line 613, in test_model_fn
    ret = model(input_, p2v_map, coords_float, coords[:, 0].int(), batch_offsets, epoch, ins_sample_num=-1, training=False)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/xiaodchen/Generalization/DyCo3D/model/pointgroup/pointgroup.py", line 574, in forward
    proposal_idx, proposal_len, scores = self.generate_proposal(mask_logits.squeeze(dim=0).sigmoid(), object_idxs,
  File "/home/xiaodchen/Generalization/DyCo3D/model/pointgroup/pointgroup.py", line 454, in generate_proposal
    proposal_idx = torch.cat(proposal_idx, dim=0)
RuntimeError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradNestedTensor, UNKNOWN_TENSOR_TYPE_ID, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, Autocast, Batched, VmapMode].

**Comment by tonghe90** [comment]
That depends on the model you use. If the channel unit (the value of m in the config file) is 16, 1080TI (11G) should be good
